import { getDynamicPeriodOptions } from "./datePeriodUtils.js";

const dynamicPeriods = getDynamicPeriodOptions();

const leadDashboardData = {
  period: {
    selected: dynamicPeriods.selected,
    options: dynamicPeriods.options,
  },
  kpis: [
    {
      key: "newLeads",
      label: "New Leads",
      value: "248",
      change: "+12%",
      comparison: "vs. last period",
      trend: "up",
      icon: "users",
      tone: "blue",
      sparkline: [52, 70, 64, 88, 82, 104, 118],
    },
    {
      key: "contacted",
      label: "Contacted",
      value: "186",
      change: "+18%",
      comparison: "vs. last period",
      trend: "up",
      icon: "message",
      tone: "purple",
      sparkline: [44, 58, 61, 72, 69, 85, 96],
    },
    {
      key: "qualified",
      label: "Qualified",
      value: "102",
      change: "+22%",
      comparison: "vs. last period",
      trend: "up",
      icon: "check",
      tone: "green",
      sparkline: [28, 37, 42, 39, 52, 57, 65],
    },
    {
      key: "converted",
      label: "Converted",
      value: "48",
      change: "+27%",
      comparison: "vs. last period",
      trend: "up",
      icon: "target",
      tone: "orange",
      sparkline: [14, 18, 17, 24, 23, 29, 34],
    },
    {
      key: "conversionRate",
      label: "Conversion Rate",
      value: "19.4%",
      change: "+3.2%",
      comparison: "vs. last period",
      trend: "up",
      icon: "chart",
      tone: "sky",
      sparkline: [9, 10, 11, 10, 12, 13, 15],
    },
  ],
  volume: [
    {
      key: "today",
      label: "Today's Leads",
      value: "32",
      change: "+28%",
      detail: "vs. yesterday (25)",
      tone: "green",
      icon: "calendar",
    },
    {
      key: "weekly",
      label: "Weekly Leads",
      value: "142",
      change: "+16%",
      detail: "vs. previous week (122)",
      tone: "blue",
      icon: "bar",
    },
    {
      key: "monthly",
      label: "Monthly Leads",
      value: "624",
      change: "+20%",
      detail: "vs. previous month (520)",
      tone: "sky",
      icon: "calendar2",
    },
    {
      key: "total",
      label: "Total Leads",
      value: "2,480",
      detail: "All time leads",
      tone: "purple",
      icon: "database",
    },
  ],
  selectedLead: {
    id: "lead-1025",
    name: "Rakesh Kumar",
    initials: "RK",
    email: "rakesh.kumar@example.com",
    phone: "+91 98765 43210",
    interestedCourse: "B.Tech (CSE)",
    feesQuery: "Yes",
    hostelQuery: "Yes",
    hostelFees: "Requested",
    location: "Delhi",
    additionalNotes: "Interested in scholarships and placement details.",
    status: "Qualified",
    source: "Website",
    lastActivity: "10 minutes ago",
  },
  leadOptions: [
    { id: "lead-1025", name: "Rakesh Kumar" },
    { id: "lead-1024", name: "Aarav Sharma" },
    { id: "lead-1023", name: "Priya Patel" },
    { id: "lead-1022", name: "Rohit Mehta" },
  ],
  conversation: [
    {
      id: "message-1",
      role: "lead",
      text: "Hi, I want to know about B.Tech courses.",
      time: "10:24 AM",
    },
    {
      id: "message-2",
      role: "assistant",
      text: "Sure! We offer B.Tech in CSE, ECE, ME and more. Which branch are you interested in?",
      time: "10:24 AM",
    },
    {
      id: "message-3",
      role: "lead",
      text: "CSE. Also tell me about fees and hostel facilities.",
      time: "10:25 AM",
    },
    {
      id: "message-4",
      role: "assistant",
      text: "The annual fees for B.Tech CSE is ₹1,20,000. We also provide hostel facilities with separate rooms for boys and girls. Would you like to know the hostel fees?",
      time: "10:26 AM",
    },
  ],
  pipeline: [
    { stage: "New Leads", value: 248, percent: "100%", color: "#2563eb" },
    { stage: "Contacted", value: 180, percent: "73%", color: "#16a34a" },
    { stage: "Qualified", value: 96, percent: "39%", color: "#f97316" },
    { stage: "Converted", value: 64, percent: "26%", color: "#8b5cf6" },
  ],
  sources: [
    { source: "Website", value: 86, color: "#2563eb" },
    { source: "WhatsApp", value: 62, color: "#16a34a" },
    { source: "Social Media", value: 42, color: "#8b5cf6" },
    { source: "Referral", value: 28, color: "#f59e0b" },
    { source: "Email Campaign", value: 18, color: "#06b6d4" },
    { source: "Others", value: 12, color: "#94a3b8" },
  ],
  counsellors: [
    {
      rank: 1,
      name: "Neha Sharma",
      initials: "NS",
      totalLeads: 54,
      contacted: 42,
      qualified: 28,
      converted: 16,
      conversionRate: "29.6%",
    },
    {
      rank: 2,
      name: "Rohit Verma",
      initials: "RV",
      totalLeads: 48,
      contacted: 36,
      qualified: 24,
      converted: 12,
      conversionRate: "25.0%",
    },
    {
      rank: 3,
      name: "Priya Singh",
      initials: "PS",
      totalLeads: 37,
      contacted: 28,
      qualified: 18,
      converted: 9,
      conversionRate: "24.3%",
    },
    {
      rank: 4,
      name: "Aman Khan",
      initials: "AK",
      totalLeads: 32,
      contacted: 22,
      qualified: 14,
      converted: 7,
      conversionRate: "21.9%",
    },
    {
      rank: 5,
      name: "Sneha Patel",
      initials: "SP",
      totalLeads: 28,
      contacted: 18,
      qualified: 11,
      converted: 5,
      conversionRate: "17.9%",
    },
  ],
};

export default leadDashboardData;
