const kpis = [
  {
    key: "today",
    label: "Today's Leads",
    value: 0,
    change: "+0%",
    comparison: "vs. yesterday (0)",
    icon: "calendar",
    tone: "emerald",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
  },
  {
    key: "weekly",
    label: "Weekly Leads",
    value: 0,
    change: "+0%",
    comparison: "vs. previous week (0)",
    icon: "bar",
    tone: "sky",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
  },
  {
    key: "monthly",
    label: "Monthly Leads",
    value: 0,
    change: "+0%",
    comparison: "vs. previous month (0)",
    icon: "calendar2",
    tone: "violet",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
  },
  {
    key: "total",
    label: "Total Leads",
    value: 0,
    change: null,
    comparison: "All time leads",
    icon: "database",
    tone: "orange",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
  },
];

import { getDynamicPeriodOptions } from "./datePeriodUtils.js";

const dynamicPeriods = getDynamicPeriodOptions();

const period = {
  selected: dynamicPeriods.selected,
  options: dynamicPeriods.studentOptions,
};

const avatarColors = [
  "bg-gradient-to-br from-blue-400 to-blue-600",
  "bg-gradient-to-br from-purple-400 to-purple-600",
  "bg-gradient-to-br from-blue-500 to-indigo-600",
  "bg-gradient-to-br from-amber-400 to-orange-500",
  "bg-gradient-to-br from-sky-400 to-blue-600",
  "bg-gradient-to-br from-emerald-400 to-emerald-600",
  "bg-gradient-to-br from-fuchsia-400 to-purple-600",
  "bg-gradient-to-br from-green-500 to-emerald-700",
];

const statusStyles = {
  New: "bg-blue-50 text-blue-700 border border-blue-100",
  Contacted: "bg-purple-50 text-purple-700 border border-purple-100",
  Qualified: "bg-green-50 text-green-700 border border-green-100",
  Converted: "bg-orange-50 text-orange-700 border border-orange-100",
};

const studentLeads = [
  {
    id: "lead-1",
    initials: "AS",
    avatarColorIdx: 0,
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    phone: "+91 98765 43210",
    coursesInterested: "B.Tech (CSE)",
    leadSource: "Website",
    status: "New",
    addedOn: "15 Sep 2025",
  },
  {
    id: "lead-2",
    initials: "RS",
    avatarColorIdx: 1,
    name: "Riya Singh",
    email: "riya.singh@example.com",
    phone: "+91 87654 32109",
    coursesInterested: "BBA",
    leadSource: "WhatsApp",
    status: "Contacted",
    addedOn: "15 Sep 2025",
  },
  {
    id: "lead-3",
    initials: "KM",
    avatarColorIdx: 2,
    name: "Karan Malhotra",
    email: "karan.m@example.com",
    phone: "+91 76543 21098",
    coursesInterested: "MBBS",
    leadSource: "Social Media",
    status: "Qualified",
    addedOn: "14 Sep 2025",
  },
  {
    id: "lead-4",
    initials: "SP",
    avatarColorIdx: 3,
    name: "Sneha Patel",
    email: "sneha.patel@example.com",
    phone: "+91 65432 10987",
    coursesInterested: "B.Tech (ECE)",
    leadSource: "Referral",
    status: "New",
    addedOn: "14 Sep 2025",
  },
  {
    id: "lead-5",
    initials: "AV",
    avatarColorIdx: 4,
    name: "Aditya Verma",
    email: "aditya.verma@example.com",
    phone: "+91 74321 09876",
    coursesInterested: "B.Com",
    leadSource: "Website",
    status: "Contacted",
    addedOn: "13 Sep 2025",
  },
  {
    id: "lead-6",
    initials: "PM",
    avatarColorIdx: 5,
    name: "Priya Mehta",
    email: "priya.mehta@example.com",
    phone: "+91 73210 98765",
    coursesInterested: "BCA",
    leadSource: "Email Campaign",
    status: "Qualified",
    addedOn: "13 Sep 2025",
  },
  {
    id: "lead-7",
    initials: "RG",
    avatarColorIdx: 6,
    name: "Rohit Gupta",
    email: "rohit.gupta@example.com",
    phone: "+91 72109 87654",
    coursesInterested: "B.Tech (Mechanical)",
    leadSource: "WhatsApp",
    status: "Converted",
    addedOn: "12 Sep 2025",
  },
  {
    id: "lead-8",
    initials: "AR",
    avatarColorIdx: 7,
    name: "Ananya Rao",
    email: "ananya.rao@example.com",
    phone: "+91 71098 76543",
    coursesInterested: "Design (UI/UX)",
    leadSource: "Others",
    status: "New",
    addedOn: "12 Sep 2025",
  },
];

const leadDetails = {
  "lead-1": {
    name: "Aarav Sharma",
    initials: "AS",
    avatarColorIdx: 0,
    status: "New",
    source: "Website",
    lastActivity: "Just now",
    chat: [
      { id: 1, role: "lead", text: "Hi, I want to know about B.Tech course.", time: "10:24 AM" },
      { id: 2, role: "assistant", text: "Sure! We offer B.Tech in CSE, ECE, ME and more. Which branch are you interested in?", time: "10:24 AM" },
      { id: 3, role: "lead", text: "CSE. Also tell me about fees and hostel facilities.", time: "10:26 AM" },
      { id: 4, role: "assistant", text: "The annual fees for B.Tech CSE is ₹1,20,000. We also provide hostel facilities with separate rooms for boys and girls. Would you like to know the hostel fees?", time: "10:26 AM" },
      { id: 5, role: "lead", text: "Yes, please share the details.", time: "10:28 AM" },
      { id: 6, role: "assistant", text: "Hostel fees is ₹45,000 per year including mess. Do you have any other queries?", time: "10:28 AM" },
    ],
    keyInfo: {
      Name: "Aarav Sharma",
      Email: "aarav.sharma@example.com",
      Phone: "+91 98765 43210",
      "Interested Course": "B.Tech (CSE)",
      "Fees Query": "Yes",
      "Hostel Query": "Yes",
      "Preferred Intake": "2026",
      "Lead Source": "Website",
      Location: "Delhi",
      Status: "New",
      "Additional Notes": "Interested in scholarships and placement details.",
      "Created On": "15 Sep 2025, 10:24 AM",
      "Assigned To": "Rakesh Kumar",
    },
  },
  "lead-2": {
    name: "Riya Singh",
    initials: "RS",
    avatarColorIdx: 1,
    status: "Contacted",
    source: "WhatsApp",
    lastActivity: "2 hours ago",
    chat: [
      { id: 1, role: "lead", text: "Hello, I want to take admission in BBA.", time: "09:12 AM" },
      { id: 2, role: "assistant", text: "Hello Riya! Great choice. Our BBA program is 3 years full-time. May I know your 12th percentage?", time: "09:13 AM" },
      { id: 3, role: "lead", text: "I scored 88% in 12th commerce.", time: "09:15 AM" },
      { id: 4, role: "assistant", text: "Excellent! You are eligible for direct admission. The fees is ₹80,000 per year. Would you like to book a counselling session?", time: "09:15 AM" },
    ],
    keyInfo: {
      Name: "Riya Singh",
      Email: "riya.singh@example.com",
      Phone: "+91 87654 32109",
      "Interested Course": "BBA",
      "Fees Query": "Yes",
      "Hostel Query": "No",
      "Preferred Intake": "2026",
      "Lead Source": "WhatsApp",
      Location: "Mumbai",
      Status: "Contacted",
      "Additional Notes": "12th 88% commerce, direct admission eligible.",
      "Created On": "15 Sep 2025, 09:12 AM",
      "Assigned To": "Priya Sharma",
    },
  },
  "lead-3": {
    name: "Karan Malhotra",
    initials: "KM",
    avatarColorIdx: 2,
    status: "Qualified",
    source: "Social Media",
    lastActivity: "Yesterday",
    chat: [
      { id: 1, role: "lead", text: "MBBS ke baare mein details chahiye.", time: "Yesterday, 2:30 PM" },
      { id: 2, role: "assistant", text: "Namaste Karan! MBBS 5.5 saal ka course hai including internship. NEET qualified hona zaroori hai.", time: "Yesterday, 2:31 PM" },
      { id: 3, role: "lead", text: "Haan maine NEET diya hai, score 620 hai.", time: "Yesterday, 2:35 PM" },
      { id: 4, role: "assistant", text: "Bahut badhiya! Aap ke score ke basis par aap easily admission le sakte hain. Kya aap counselling ke liye aana chahenge?", time: "Yesterday, 2:36 PM" },
    ],
    keyInfo: {
      Name: "Karan Malhotra",
      Email: "karan.m@example.com",
      Phone: "+91 76543 21098",
      "Interested Course": "MBBS",
      "Fees Query": "Yes",
      "Hostel Query": "Yes",
      "Preferred Intake": "2026",
      "Lead Source": "Social Media",
      Location: "Jaipur",
      Status: "Qualified",
      "Additional Notes": "NEET score: 620, qualified for counselling.",
      "Created On": "14 Sep 2025, 02:30 PM",
      "Assigned To": "Dr. Ankit Verma",
    },
  },
  "lead-4": {
    name: "Sneha Patel",
    initials: "SP",
    avatarColorIdx: 3,
    status: "New",
    source: "Referral",
    lastActivity: "Yesterday",
    chat: [
      { id: 1, role: "lead", text: "Meri friend ne aapka college suggest kiya, ECE branch mein interest hai.", time: "Yesterday, 11:02 AM" },
      { id: 2, role: "assistant", text: "Welcome Sneha! B.Tech ECE bahut hi accha branch hai. 4 years ka course hai.", time: "Yesterday, 11:03 AM" },
    ],
    keyInfo: {
      Name: "Sneha Patel",
      Email: "sneha.patel@example.com",
      Phone: "+91 65432 10987",
      "Interested Course": "B.Tech (ECE)",
      "Fees Query": "No",
      "Hostel Query": "No",
      "Preferred Intake": "2026",
      "Lead Source": "Referral",
      Location: "Ahmedabad",
      Status: "New",
      "Additional Notes": "Referred by current student.",
      "Created On": "14 Sep 2025, 11:02 AM",
      "Assigned To": "Unassigned",
    },
  },
  "lead-5": {
    name: "Aditya Verma",
    initials: "AV",
    avatarColorIdx: 4,
    status: "Contacted",
    source: "Website",
    lastActivity: "2 days ago",
    chat: [
      { id: 1, role: "lead", text: "B.Com ke liye fees kitni hai?", time: "2 days ago, 3:15 PM" },
      { id: 2, role: "assistant", text: "Namaste Aditya! B.Com 3 years ka course hai, annual fees ₹45,000 hai.", time: "2 days ago, 3:16 PM" },
      { id: 3, role: "lead", text: "Ok, scholarship ka koi provision hai?", time: "2 days ago, 3:20 PM" },
    ],
    keyInfo: {
      Name: "Aditya Verma",
      Email: "aditya.verma@example.com",
      Phone: "+91 74321 09876",
      "Interested Course": "B.Com",
      "Fees Query": "Yes",
      "Hostel Query": "No",
      "Preferred Intake": "2026",
      "Lead Source": "Website",
      Location: "Lucknow",
      Status: "Contacted",
      "Additional Notes": "Asked about scholarship options.",
      "Created On": "13 Sep 2025, 03:15 PM",
      "Assigned To": "Rohit Tiwari",
    },
  },
  "lead-6": {
    name: "Priya Mehta",
    initials: "PM",
    avatarColorIdx: 5,
    status: "Qualified",
    source: "Email Campaign",
    lastActivity: "2 days ago",
    chat: [
      { id: 1, role: "lead", text: "Email mein jo BCA course ke baare mein aya tha, uska placement record kaisa hai?", time: "2 days ago, 10:40 AM" },
      { id: 2, role: "assistant", text: "Hi Priya! BCA mein last year 92% placement hua tha, average package ₹4.5 LPA hai.", time: "2 days ago, 10:41 AM" },
      { id: 3, role: "lead", text: "Great, admission process kya hai?", time: "2 days ago, 10:45 AM" },
    ],
    keyInfo: {
      Name: "Priya Mehta",
      Email: "priya.mehta@example.com",
      Phone: "+91 73210 98765",
      "Interested Course": "BCA",
      "Fees Query": "No",
      "Hostel Query": "No",
      "Preferred Intake": "2026",
      "Lead Source": "Email Campaign",
      Location: "Bhopal",
      Status: "Qualified",
      "Additional Notes": "Interested in placements, process shared.",
      "Created On": "13 Sep 2025, 10:40 AM",
      "Assigned To": "Sneha Kapoor",
    },
  },
  "lead-7": {
    name: "Rohit Gupta",
    initials: "RG",
    avatarColorIdx: 6,
    status: "Converted",
    source: "WhatsApp",
    lastActivity: "3 days ago",
    chat: [
      { id: 1, role: "lead", text: "B.Tech Mechanical mein admission lena hai.", time: "3 days ago, 1:20 PM" },
      { id: 2, role: "assistant", text: "Sure Rohit! Mechanical branch seats available hain. Fees ₹1,10,000 per year.", time: "3 days ago, 1:21 PM" },
    ],
    keyInfo: {
      Name: "Rohit Gupta",
      Email: "rohit.gupta@example.com",
      Phone: "+91 72109 87654",
      "Interested Course": "B.Tech (Mechanical)",
      "Fees Query": "Yes",
      "Hostel Query": "Yes",
      "Preferred Intake": "2026",
      "Lead Source": "WhatsApp",
      Location: "Kanpur",
      Status: "Converted",
      "Additional Notes": "Admission confirmed, fees paid.",
      "Created On": "12 Sep 2025, 01:20 PM",
      "Assigned To": "Amit Joshi",
    },
  },
  "lead-8": {
    name: "Ananya Rao",
    initials: "AR",
    avatarColorIdx: 7,
    status: "New",
    source: "Others",
    lastActivity: "3 days ago",
    chat: [
      { id: 1, role: "lead", text: "UI/UX Design course hai kya aapke yahan?", time: "3 days ago, 11:45 AM" },
      { id: 2, role: "assistant", text: "Hi Ananya! Haan hum Diploma in UI/UX Design offer karte hain — 1 year ka certification course.", time: "3 days ago, 11:46 AM" },
    ],
    keyInfo: {
      Name: "Ananya Rao",
      Email: "ananya.rao@example.com",
      Phone: "+91 71098 76543",
      "Interested Course": "Design (UI/UX)",
      "Fees Query": "No",
      "Hostel Query": "No",
      "Preferred Intake": "2026",
      "Lead Source": "Others",
      Location: "Bangalore",
      Status: "New",
      "Additional Notes": "Interested in 1 year diploma.",
      "Created On": "12 Sep 2025, 11:45 AM",
      "Assigned To": "Unassigned",
    },
  },
};

export default {
  kpis,
  period,
  studentLeads,
  leadDetails,
  avatarColors,
  statusStyles,
};
