// Static mock data for Campaigns UI prototype (Frontend-only)

export const MOCK_CAMPAIGNS = [
  {
    id: "campaign-1",
    name: "B.Tech Admissions October 2026",
    description: "Promotional campaign for upcoming B.Tech admissions with special offer.",
    audience: "B.Tech Interested (2,850 leads)",
    audienceCount: 2850,
    template: "admission_offer",
    templateStatus: "Approved",
    scheduleType: "Send Now",
    scheduledAt: "25 Sep 2026, 06:00 PM",
    status: "Completed",
    sent: 2850,
    delivered: 2650,
    read: 2120,
    replied: 340,
    failed: 28,
    createdOn: "24 Sep 2026",
  },
  {
    id: "campaign-2",
    name: "MBA Counselling Drive",
    description: "Invite MBA prospects for 1-on-1 virtual counselling sessions.",
    audience: "MBA Interested (1,320 leads)",
    audienceCount: 1320,
    template: "counselling_invite",
    templateStatus: "Approved",
    scheduleType: "Schedule for Later",
    scheduledAt: "26 Sep 2026, 11:00 AM",
    status: "Sending",
    sent: 1320,
    delivered: 1100,
    read: 850,
    replied: 120,
    failed: 15,
    createdOn: "24 Sep 2026",
  },
  {
    id: "campaign-3",
    name: "Fee Reminder Campaign",
    description: "Follow-up reminder for pending admission fee submissions.",
    audience: "Not Contacted (3,450 leads)",
    audienceCount: 3450,
    template: "fee_reminder",
    templateStatus: "Approved",
    scheduleType: "Schedule for Later",
    scheduledAt: "28 Sep 2026, 10:00 AM",
    status: "Scheduled",
    sent: 0,
    delivered: 0,
    read: 0,
    replied: 0,
    failed: 0,
    createdOn: "23 Sep 2026",
  },
  {
    id: "campaign-4",
    name: "Scholarship Awareness",
    description: "Inform leads about merit-based scholarship schemes.",
    audience: "All Leads (12,430 leads)",
    audienceCount: 12430,
    template: "scholarship_info",
    templateStatus: "Approved",
    scheduleType: "Draft",
    scheduledAt: "—",
    status: "Draft",
    sent: 0,
    delivered: 0,
    read: 0,
    replied: 0,
    failed: 0,
    createdOn: "22 Sep 2026",
  },
  {
    id: "campaign-5",
    name: "Hostel Facility Info",
    description: "Brochure and virtual tour details for campus hostels.",
    audience: "Counselling Booked (980 leads)",
    audienceCount: 980,
    template: "hostel_info",
    templateStatus: "Approved",
    scheduleType: "Cancelled",
    scheduledAt: "—",
    status: "Cancelled",
    sent: 0,
    delivered: 0,
    read: 0,
    replied: 0,
    failed: 0,
    createdOn: "20 Sep 2026",
  },
];

export const MOCK_AUDIENCE_GROUPS = [
  { id: "g1", name: "All Leads", count: 12430, checked: false },
  { id: "g2", name: "B.Tech Interested", count: 2850, checked: true },
  { id: "g3", name: "MBA Interested", count: 1320, checked: false },
  { id: "g4", name: "Counselling Booked", count: 980, checked: false },
  { id: "g5", name: "Not Contacted", count: 3450, checked: false },
];

export const MOCK_TEMPLATES = [
  {
    id: "admission_offer",
    name: "admission_offer",
    status: "Approved",
    language: "en",
    category: "MARKETING",
    vars: [
      { key: "1", name: "Student Name", example: "John" },
      { key: "2", name: "Course Name", example: "B.Tech" },
      { key: "3", name: "Offer Details", example: "10% OFF" },
    ],
    previewText:
      "Hi {{1}},\n\nExciting news! 🎉\nGet {{3}} on {{2}} admissions for the upcoming session.\n\nClick below to know more or reply for counselling.",
  },
  {
    id: "counselling_invite",
    name: "counselling_invite",
    status: "Approved",
    language: "en",
    category: "UTILITY",
    vars: [
      { key: "1", name: "Student Name", example: "Rahul" },
      { key: "2", name: "Date & Time", example: "Tomorrow 3 PM" },
    ],
    previewText:
      "Hello {{1}},\n\nYour 1-on-1 admission counselling session is scheduled for {{2}}.\n\nPlease reply CONFIRM to accept.",
  },
  {
    id: "fee_reminder",
    name: "fee_reminder",
    status: "Approved",
    language: "en",
    category: "UTILITY",
    vars: [
      { key: "1", name: "Student Name", example: "Pooja" },
      { key: "2", name: "Due Date", example: "30th Sept" },
    ],
    previewText:
      "Dear {{1}},\n\nThis is a friendly reminder that your course registration fee is due by {{2}}.\n\nReply for payment portal link.",
  },
];

export const MOCK_RECIPIENT_STATUSES = [
  {
    name: "Amit Kumar",
    phone: "+91 9876543210",
    status: "Delivered",
    sentAt: "11:32 AM",
    deliveredAt: "11:32 AM",
    readAt: "11:45 AM",
  },
  {
    name: "Neha Sharma",
    phone: "+91 9123456789",
    status: "Read",
    sentAt: "11:32 AM",
    deliveredAt: "11:33 AM",
    readAt: "11:46 AM",
  },
  {
    name: "Rahul Verma",
    phone: "+91 9988776655",
    status: "Replied",
    sentAt: "11:32 AM",
    deliveredAt: "11:33 AM",
    readAt: "11:50 AM",
  },
  {
    name: "Pooja Singh",
    phone: "+91 9811223344",
    status: "Delivered",
    sentAt: "11:32 AM",
    deliveredAt: "11:34 AM",
    readAt: "11:48 AM",
  },
  {
    name: "Vikram Patel",
    phone: "+91 9744556677",
    status: "Failed",
    sentAt: "11:32 AM",
    deliveredAt: "—",
    readAt: "—",
  },
  {
    name: "Saurabh Chandra",
    phone: "+91 9655443322",
    status: "Read",
    sentAt: "11:32 AM",
    deliveredAt: "11:35 AM",
    readAt: "11:52 AM",
  },
  {
    name: "Ananya Roy",
    phone: "+91 9544332211",
    status: "Replied",
    sentAt: "11:32 AM",
    deliveredAt: "11:36 AM",
    readAt: "11:55 AM",
  },
];
